import { defineConfig } from 'vite';
import { ViteEjsPlugin } from 'vite-plugin-ejs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { glob } from 'glob';
import copy from 'rollup-plugin-copy';
import liveReload from 'vite-plugin-live-reload';

const defaultBase = '/outfitpals/';

function resolveBase(command: 'serve' | 'build') {
  if (command === 'serve') return '/';

  const envBase = process.env.VITE_BASE_PATH;

  const normalized =
    envBase && envBase.trim()
      ? `/${envBase.replace(/^\/+|\/+$/g, '')}/`
      : defaultBase;
  return normalized;
}

function moveOutputPlugin() {
  return {
    name: 'move-output',
    enforce: 'post',
    apply: 'build',
    generateBundle(_options: any, bundle: any) {
      for (const fileName in bundle) {
        if (fileName.startsWith('pages/')) {
          const newFileName = fileName.slice('pages/'.length);
          bundle[fileName].fileName = newFileName;
        }
      }
    },
  };
}

export default defineConfig(({ command, base }) => {
  const basePath = resolveBase(command);

  return {

    base: basePath,

    plugins: [
      liveReload(['./layout/**/*.ejs', './pages/**/*.ejs', './pages/**/*.html']),

      ViteEjsPlugin(() => ({
        BASE_URL: basePath,
      })),

      copy({
        targets: [
          {
            src: 'assets/images/**/*',
            dest: 'dist/assets/images',
          },
        ],
        hook: 'writeBundle',
        verbose: false,
      }),

      moveOutputPlugin(),
    ],

    server: {
      // 啟動 server 時預設開啟的頁面
      open: 'pages/index.html',
    },

    build: {
      outDir: 'dist',
      rollupOptions: {
        input: Object.fromEntries(
          glob.sync('pages/**/*.html').map((file) => [
            path.relative('pages', file.slice(0, file.length - path.extname(file).length)),
            fileURLToPath(new URL(file, import.meta.url)),
          ])
        ),
      },
    },
  };
});
